project: dis-vocalset
dir: /home/russell/src/dis-vocalset/data
device: "cuda:0"
wandb: True
entity: russellizadilocal
notes: "gvae"
tags: ["eval", ]

data:
  vocalset:
    root: /ext/projects/disentangle/datasets/vocalset
    seed: 42
    ratio: .9
  sample_rate: &sample_rate 16000
  norm: true

  features:
    sample_rate: *sample_rate
    n_fft: 4096 # 2048
    win_length: 4096 # 2048
    hop_length: 2048 # 1024
    n_mels: 16
    power: 2

  attrs: &attrs [
    singer, 
    context,
    technique,
    vowel]

  loader:
    batch_size: 120
    shuffle: false
    drop_last: false
    num_workers: 16
    pin_memory: True

model:
  name: gvae
  # path: data/wandb/run-20230702_190931-qu8nacem/files/model.pth # mlvae
  path: data/wandb/run-20230701_122924-x2tplrhk/files/model.pth # gvae
  # path: data/wandb/run-20230701_122744-r3epu8w7/files/model.pth # svae
  encoder:
    d_input: &d_input 16
    d_hidden: &d_hidden 1024
    d_latent: 4 # 2 * d_latent
    n_heads: &n_heads 2
    n_layers: &n_leayers 2
    max_duration: &max_duration 1024
    rates: [0, 0, 0, 0]
  decoder:
    d_latent: &d_latent 2
    d_hidden: *d_hidden
    d_output: *d_input
    n_attrs: 4
    n_heads: *n_heads
    n_layers: *n_leayers
    max_duration: *max_duration
  
  prior:
    dim: *d_latent
  
  posterior_q:
    dim: *d_latent
  
  posterior_p:
    dim: *d_latent
